version: '3'
services:
  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-452915/image-registry/client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222  
  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-452915/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
  products-ms:
    build: 
      context: ./Products-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-452915/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-452915/image-registry/orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - "${PAYMENTS_PORT}:${PAYMENTS_PORT}"
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-452915/image-registry/payments-ms
    environment:
      - PORT=${PAYMENTS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_PAYMENT_SUCCESS_URL=${STRIPE_PAYMENT_SUCCESS_URL}
      - STRIPE_PAYMENT_CANCEL_URL=${STRIPE_PAYMENT_CANCEL_URL}
